[dev]
port = 8080
open = true
watch = true

[dev.static]
mime_types = [
    { extension = "html", mime_type = "text/html" },
    { extension = "js", mime_type = "application/javascript" },
    { extension = "css", mime_type = "text/css" },
]

[build]
# WARNING these do nothing ??? so set in prod.sh instead
#
# MUST match eg https://n-prat.github.io/group-live-tracker/
# public_url = "/group-live-tracker/"
# public_url = "https://n-prat.github.io/group-live-tracker/"
# public_url = "."
